### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by Inferencer** [YuDeng/Portrait-4D#1]
No issues, just wanted to say congratulations it's a clever approach and the results look amazing,
There was a recent paper called InvertAvatar: Incremental GAN Inversion for Generalized Head Avatars, and another called EMO: Emote Portrait Alive
but I think yours is SOTA so a round of applause for you!  

I look forward to release and can't wait to tinker with the code & train new models where applicable

**Comment by Inferencer** [comment]
actually one issue, there seems to be a difference between Portrait-4D and Portait-4D V2 with no paper link on the project page of v2, Should I refer to Portrait-4D's paper or will you be releasing a separate paper for V2?

**Comment by YuDeng** [comment]
> actually one issue, there seems to be a difference between Portrait-4D and Portait-4D V2 with no paper link on the project page of v2, Should I refer to Portrait-4D's paper or will you be releasing a separate paper for V2?

Thanks for your interest. The paper for Portrait4D-v2 can be found on arxiv now: https://arxiv.org/abs/2403.13570

**Comment by YuDeng** [comment]
Currently we only plan to release v1 in April. But we will promote the open source of v2 as soon as possible.

**Comment by skyler14** [comment]
Is there any updates?
