### ISSUE TITLE
About the motion extraction model

### ISSUE THREAD

**Issue by FacePoluke** [YuDeng/Portrait-4D#5]
Thank your excellent work!
The driving effect of your portrait4dv2 feels better than that of portrait4d. Does portrait4dv2 also use the same motion extraction network, which is the same as PDFGC?

**Comment by YuDeng** [comment]
Hi, we use the same PDFGC for v1 and v2. The main differences between them are the training strategy and data. V2 uses real video data for training so its motion control is more natural.
